dict_images = {
    'img50.jpg': "balloons soaring over a rocky, desert landscape, with a vast expanse of rock formations and turfed hill areas",
    'img49.jpg': "a scenic road winding through a tropical landscape at sunset, featuring tall palm trees on both sides and a vibrant orange and yellow sky",
    'img48.jpg': "a picturesque park featuring a winding path lined with vibrant flowers, trees, and a lamppost, set against a backdrop of a clear blue sky and lush greenery",
    'img47.jpg': "a series of layered silhouetted mountains that rise abruptly from a foreground of rugged, rocky terrain, with a single person standing on a peak in the distance",
    'img46.jpg': "a lighthouse sits atop a rugged cliff, overlooking a rough sea with waves crashing against the rocks",
    'img45.jpg': "a forest of towering trees, many with green needles and some with straight trunks",
    'img44.jpg': "a lake framed by yellow tree leaves and brushy hills with pine backdrop and snow-covered mountains in the distance",
    'img43.jpg': "a dense forest of trees in the foreground, with large dark mountains in the distance and a blue sky with orange clouds",
    'img42.jpg': "a pagoda towers standing out against the snow-capped Mount Fuji with its red and white colors, accompanied by a grey sky",
    'img41.jpg': 'a person walking on the beach with a rocky coastline, shallow waters and a small boat in the distance',
    'img40.jpg': "a grassy field, with a pink cloth serving as a table adorned with various items, arranged in a picturesque landscape",
    'img39.jpg': "a small house perched on the edge of a crystal-clear lake, with towering snow-capped mountains in the background",
    'img38.jpg': "lush greenery comprising sturdy evergreen trees and leafy green plants, spanning the valley below the rocky mountains",
    'img37.jpg': "a landscape dominated by a line of mountains, featuring a peaceful lake nestled between rolling hills, scattered with small wooden barns",
    'img36.jpg': "a majestic waterfall flows down a rugged cliff, surrounded by sunlit trees, during dusk",
    'img35.jpg': "a vibrant forest in the midst of a sunny day, with bright sunbeams illuminating from behind the trees and lush ferns covering the forest floor",
    'img34.jpg': "a lake nestled in the mountains, surrounded by lush trees and majestic snow-capped peaks reflected in the calm surface of the water",
    'img33.jpg': "a large foreign castle sits atop the end of craggy mountain ranges, partially bathed in sunlight in the early morning",
    'img32.jpg': "a picturesque rural landscape featuring houses dotting rolling green hills that lead to tall mountains under an early morning or late afternoon sky",
    'img31.jpg': "a few buildings nestled amongst the rolling green hills and distant mountains under a clear blue sky",
    'img30.jpg': "a serene sunbeam filtering through light green pine needles, bathing the brown earth below in a warm glow, likely during autumn",
    'img29.jpg': "a large bush-clad concrete or stone house by an ever-flowing stream, surrounded by vegetation and a patchwork of forested, barren and grassy hills",
    'img28.jpg': "a woman sitting in a lush grassy field, with a rustic wooden cabin and a majestic tree standing tall nearby",
    'img27.jpg': "a majestic snow-capped volcano is set against a vibrant purple sky, with lush greenery and dry grass in the foreground",
    'img26.jpg': "a seagull is flying over an ocean full of small waves with a sea of fog surrounding everything",
    'img25.jpg': "a rustic chair positioned on a lush grassy field in front of a patchwork of misty evergreens",
    'img24.jpg': "hills of a lush, grassy field set against a majestic mountain range, bathed in warm sunlight",
    'img23.jpg': "a majestic mountain range set against a vibrant pink sky, with a radiant white sun positioned above the mountains",
    'img22.jpg': "a serene riverside scene with houses surrounded by trees and grass",
    'img21.jpg': "a small town on a island in the middle of a lake with a mountain range in the background and a reflection of it in the lake's calm and still water",
    'img20.jpg': 'a mountain range with a volcano emitting steam, set against a starry sky in shades of pink and purple',
    'img19.jpg': 'a natural arch in a rocky landscape, with a pinkish-orange hue and cracked rock formations stretching out into the distance',
    'img18.jpg': 'a path through the forest is covered with fallen leaves and surrounded by thick trees with light shining through the misty fog',
    'img17.jpg': 'a small house sits on the side of a mountain, surrounded by staircase rice fields, with sunlight shining behind the household',
    'img16.jpg': 'a stunning winter landscape at sunrise or sunset, featuring a majestic snow-covered Nordic fir tree in the foreground',
    'img15.jpg': 'a mountain range featuring altitude snow and glaciers',
    "img14.jpg": "a tree hangs over the glowing lights and swirling waters, which boat canoes and ducks glide through, with a distant bridge and hedge lining that frame a long walkway and short dock",
    "img13.jpg": "a half-moon over a snow-capped mountain range, striking a balance between what would appear grey and coppery red tones",
    "img12.jpg": "a person holding a bouquet of wildflowers against the backdrop of a lush, open landscape, with the flowers and the greenery reflected in the water",
    "img11.jpg": "a picturesque cliffside overlooking the ocean, with a majestic building perched precariously on a stone ledge at the top",
    "img10.jpg": "a waterfall cascading down moss-covered rocks, with a group of people standing on the rock above",
    "img9.jpg" : "a landscape of dry, rolling hills with hot air balloons floating in the sky above them",
    "img8.jpg" : "three pine trees frame the moon and a pink- and purple-hued sky",
    "img7.jpg" : "silhouettes of two people from behind, facing a mountainous forest below snow-covered peaks" ,
    "img6.jpg" : "a lighthouse situated on a rocky coastline, with the calm sea and cloudy sky",
    "img5.jpg" : "vibrant purple bushes lining the sides of a dirt path along a serene and peaceful-looking field leading to open space",
    "img4.jpg" : "a mountainous landscape featuring a snowy mountain peak, a lake, flowing water, a yellow dandelion, and lush greenery in the foreground",
    "img3.jpg" : "a rustic landscape featuring a flock of grazing sheep in the foreground and a breathtaking mountainous backdrop",
    "img2.jpg" : "a breathtaking view from an elevated, rocky perch overlooking a vast body of water, adorned with multiple peninsulas and craggy islands spread out along the shoreline",
    "img1.jpg" : "a breathtaking mountain landscape during winter, where snow-covered peaks meet the golden light of a rising or setting sun",
}